# Generated by Django 5.0.14 on 2025-09-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblProject_withUserNames',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Prism.tblproject',),
        ),
    ]
