# Generated by Django 5.0.14 on 2025-09-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prism', '0002_tblproject_withusernames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblProject_withUserNames',
        ),
    ]
