# Generated by Django 5.2.8 on 2025-11-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prism', '0003_delete_tblproject_withusernames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tblprojectnotes',
        ),
    ]
