# Generated by Django 5.2.8 on 2025-11-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prism', '0004_delete_tblprojectnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblprojectnotes',
            fields=[
                ('pnid', models.AutoField(db_column='pnID', editable=False, primary_key=True, serialize=False)),
                ('projectnumber', models.CharField(blank=True, db_column='ProjectNumber', max_length=5, null=True)),
                ('pnote', models.TextField(blank=True, db_column='pNote', null=True)),
                ('created', models.DateTimeField(blank=True, db_column='Created', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblProjectNotes',
                'managed': False,
            },
        ),
    ]
