# Generated by Django 5.2.8 on 2026-02-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prism', '0005_tblprojectnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblkristal',
            fields=[
                ('kristalid', models.AutoField(db_column='KristalID', primary_key=True, serialize=False)),
                ('kristalnumber', models.IntegerField(blank=True, db_column='KristalNumber', null=True)),
                ('kristalref', models.DecimalField(blank=True, db_column='KristalRef', decimal_places=0, max_digits=6, null=True)),
                ('kristalname', models.CharField(blank=True, db_column='KristalName', max_length=500, null=True)),
                ('pi', models.IntegerField(blank=True, db_column='PI', null=True)),
                ('validfrom', models.DateTimeField(blank=True, db_column='ValidFrom', null=True)),
                ('validto', models.DateTimeField(blank=True, db_column='ValidTo', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblKristal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblusernotes',
            fields=[
                ('unid', models.AutoField(db_column='unID', editable=False, primary_key=True, serialize=False)),
                ('usernumber', models.IntegerField(blank=True, db_column='UserNumber', null=True)),
                ('unote', models.TextField(blank=True, db_column='uNote', null=True)),
                ('created', models.DateTimeField(blank=True, db_column='Created', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblUserNotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbluserproject',
            fields=[
                ('userprojectid', models.AutoField(db_column='UserProjectId', editable=False, primary_key=True, serialize=False)),
                ('usernumber', models.IntegerField(blank=True, db_column='UserNumber', null=True)),
                ('projectnumber', models.CharField(blank=True, db_column='ProjectNumber', max_length=5, null=True)),
                ('validfrom', models.DateTimeField(blank=True, db_column='ValidFrom', null=True)),
                ('validto', models.DateTimeField(blank=True, db_column='ValidTo', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblUserProject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tlkGrantStage',
            fields=[
                ('grantstageid', models.AutoField(db_column='GrantStageID', primary_key=True, serialize=False)),
                ('stagenumber', models.DecimalField(blank=True, db_column='StageNumber', decimal_places=1, max_digits=3, null=True)),
                ('grantstagedescription', models.CharField(blank=True, db_column='GrantStageDescription', max_length=25, null=True)),
                ('validfrom', models.DateTimeField(blank=True, db_column='ValidFrom', null=True)),
                ('validto', models.DateTimeField(blank=True, db_column='ValidTo', null=True)),
            ],
            options={
                'db_table': 'tlkGrantStage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tlklocation',
            fields=[
                ('locationid', models.AutoField(db_column='locationID', primary_key=True, serialize=False)),
                ('locationdescription', models.CharField(blank=True, db_column='locationDescription', max_length=100, null=True)),
                ('validfrom', models.DateTimeField(blank=True, db_column='ValidFrom', null=True)),
                ('validto', models.DateTimeField(blank=True, db_column='ValidTo', null=True)),
            ],
            options={
                'db_table': 'tlkLocation',
                'managed': False,
            },
        ),
    ]
