# Generated by Django 5.2.8 on 2026-02-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prism', '0006_tblkristal_tblusernotes_tbluserproject_tlkgrantstage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblassetgroups',
            fields=[
                ('assetid', models.AutoField(db_column='AssetID', primary_key=True, serialize=False)),
                ('project', models.CharField(blank=True, db_column='Project', max_length=5, null=True)),
                ('assetname', models.CharField(blank=True, db_column='AssetName', max_length=500, null=True)),
                ('dataowner', models.CharField(blank=True, db_column='DataOwner', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tblAssetGroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblassetschangelog',
            fields=[
                ('changeid', models.AutoField(db_column='ChangeID', primary_key=True, serialize=False)),
                ('transferfrom', models.CharField(blank=True, db_column='TransferFrom', max_length=100, null=True)),
                ('transferto', models.CharField(blank=True, db_column='TransferTo', max_length=100, null=True)),
                ('changeaccepted', models.BooleanField(blank=True, db_column='ChangeAccepted', null=True)),
                ('rejectionnotes', models.TextField(blank=True, db_column='RejectionNotes', null=True)),
            ],
            options={
                'db_table': 'tblAssetsChangeLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblassetsregister',
            fields=[
                ('fileid', models.AutoField(db_column='FileID', primary_key=True, serialize=False)),
                ('project', models.CharField(blank=True, db_column='Project', max_length=5, null=True)),
                ('datafilename', models.CharField(db_column='DataFileName', max_length=300)),
                ('vrefilepath', models.CharField(blank=True, db_column='VreFilePath', max_length=200, null=True)),
                ('datarepofilepath', models.CharField(blank=True, db_column='DataRepoFilePath', max_length=200, null=True)),
            ],
            options={
                'db_table': 'tblAssetsRegister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbldsadataowners',
            fields=[
                ('doid', models.AutoField(db_column='doID', primary_key=True, serialize=False)),
                ('dataownername', models.CharField(db_column='DataOwnerName', max_length=100, unique=True)),
                ('dataowneremail', models.CharField(blank=True, db_column='DataOwnerEmail', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblDsaDataOwners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbldsanotes',
            fields=[
                ('dnid', models.AutoField(db_column='dnID', primary_key=True, serialize=False)),
                ('dsa', models.IntegerField(db_column='Dsa')),
                ('note', models.TextField(blank=True, db_column='Note', null=True)),
                ('created', models.DateTimeField(blank=True, db_column='Created', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblDsaNotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbldsas',
            fields=[
                ('dsaid', models.AutoField(db_column='DsaID', primary_key=True, serialize=False)),
                ('documentid', models.IntegerField(db_column='DocumentID')),
                ('dsaname', models.CharField(blank=True, db_column='DsaName', max_length=100, null=True)),
                ('dsafileloc', models.CharField(blank=True, db_column='DsaFileLoc', max_length=200, null=True)),
                ('startdate', models.DateTimeField(blank=True, db_column='StartDate', null=True)),
                ('expirydate', models.DateTimeField(blank=True, db_column='ExpiryDate', null=True)),
                ('datadestructiondate', models.DateTimeField(blank=True, db_column='DataDestructionDate', null=True)),
                ('agreementowneremail', models.CharField(blank=True, db_column='AgreementOwnerEmail', max_length=50, null=True)),
                ('dspt', models.BooleanField(blank=True, db_column='DSPT', null=True)),
                ('iso27001', models.BooleanField(blank=True, db_column='ISO27001', null=True)),
                ('requiresencryption', models.BooleanField(blank=True, db_column='RequiresEncryption', null=True)),
                ('noremoteaccess', models.BooleanField(blank=True, db_column='NoRemoteAccess', null=True)),
                ('validfrom', models.DateTimeField(blank=True, db_column='ValidFrom', null=True)),
                ('validto', models.DateTimeField(blank=True, db_column='ValidTo', null=True)),
                ('deprecated', models.BooleanField(db_column='Deprecated')),
            ],
            options={
                'db_table': 'tblDsas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbldsasprojects',
            fields=[
                ('dpid', models.AutoField(db_column='dpID', primary_key=True, serialize=False)),
                ('documentid', models.IntegerField(db_column='DocumentID')),
                ('project', models.CharField(blank=True, db_column='Project', max_length=5, null=True)),
                ('validfrom', models.DateTimeField(blank=True, db_column='ValidFrom', null=True)),
                ('validto', models.DateTimeField(blank=True, db_column='ValidTo', null=True)),
            ],
            options={
                'db_table': 'tblDsasProjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblkristalnotes',
            fields=[
                ('knid', models.AutoField(db_column='knID', primary_key=True, serialize=False)),
                ('kristalnumber', models.IntegerField(blank=True, db_column='KristalNumber', null=True)),
                ('kristalnote', models.TextField(blank=True, db_column='KristalNote', null=True)),
                ('created', models.DateTimeField(blank=True, db_column='Created', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblKristalNotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltransferrequests',
            fields=[
                ('requestid', models.AutoField(db_column='RequestID', primary_key=True, serialize=False)),
                ('project', models.CharField(blank=True, db_column='Project', max_length=5, null=True)),
                ('vrenumber', models.CharField(blank=True, db_column='VreNumber', max_length=15, null=True)),
                ('requestedby', models.IntegerField(blank=True, db_column='RequestedBy', null=True)),
                ('requesternotes', models.TextField(blank=True, db_column='RequesterNotes', null=True)),
                ('reviewedby', models.IntegerField(blank=True, db_column='ReviewedBy', null=True)),
                ('reviewdate', models.DateTimeField(blank=True, db_column='ReviewDate', null=True)),
                ('reviewnotes', models.TextField(blank=True, db_column='ReviewNotes', null=True)),
            ],
            options={
                'db_table': 'tblTransferRequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tlkfiletransfermethods',
            fields=[
                ('methodid', models.AutoField(db_column='MethodID', primary_key=True, serialize=False)),
                ('methodlabel', models.CharField(blank=True, db_column='MethodLabel', max_length=30, null=True)),
                ('validfrom', models.DateTimeField(blank=True, db_column='ValidFrom', null=True)),
                ('validto', models.DateTimeField(blank=True, db_column='ValidTo', null=True)),
            ],
            options={
                'db_table': 'tlkFileTransferMethods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tlktransferrequesttypes',
            fields=[
                ('requesttypeid', models.AutoField(db_column='RequestTypeID', primary_key=True, serialize=False)),
                ('requesttypelabel', models.CharField(blank=True, db_column='RequestTypeLabel', max_length=25, null=True)),
                ('validfrom', models.DateTimeField(blank=True, db_column='ValidFrom', null=True)),
                ('validto', models.DateTimeField(blank=True, db_column='ValidTo', null=True)),
            ],
            options={
                'db_table': 'tlkTransferRequestTypes',
                'managed': False,
            },
        ),
    ]
