# Generated by Django 5.2.8 on 2026-03-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prism', '0007_tblassetgroups_tblassetschangelog_tblassetsregister_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbltransferfile',
            fields=[
                ('fileid', models.AutoField(db_column='FileID', primary_key=True, serialize=False)),
                ('filename', models.CharField(db_column='FileName', max_length=300)),
                ('trefilepath', models.CharField(blank=True, db_column='TreFilePath', max_length=200, null=True)),
                ('datarepofilepath', models.CharField(blank=True, db_column='DataRepoFilePath', max_length=200, null=True)),
                ('transferaccepted', models.BooleanField(blank=True, db_column='TransferAccepted', null=True)),
                ('rejectionnotes', models.TextField(blank=True, db_column='RejectionNotes', null=True)),
                ('validfrom', models.DateTimeField(blank=True, db_column='ValidFrom', null=True)),
                ('validto', models.DateTimeField(blank=True, db_column='ValidTo', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblTransferFile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltransferfileasset',
            fields=[
                ('assetid', models.AutoField(db_column='AssetID', primary_key=True, serialize=False)),
                ('assetname', models.CharField(blank=True, db_column='AssetName', max_length=500, null=True)),
                ('dataowner', models.CharField(blank=True, db_column='DataOwner', max_length=100, null=True)),
                ('validfrom', models.DateTimeField(blank=True, db_column='ValidFrom', null=True)),
                ('validto', models.DateTimeField(blank=True, db_column='ValidTo', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblTransferFileAsset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltransferrequest',
            fields=[
                ('requestid', models.AutoField(db_column='RequestID', primary_key=True, serialize=False)),
                ('projectnumber', models.CharField(blank=True, db_column='ProjectNumber', max_length=5, null=True)),
                ('vrenumber', models.CharField(blank=True, db_column='VreNumber', max_length=15, null=True)),
                ('requestedby', models.IntegerField(blank=True, db_column='RequestedBy', null=True)),
                ('requesternotes', models.TextField(blank=True, db_column='RequesterNotes', null=True)),
                ('reviewedby', models.IntegerField(blank=True, db_column='ReviewedBy', null=True)),
                ('reviewdate', models.DateTimeField(blank=True, db_column='ReviewDate', null=True)),
                ('reviewnotes', models.TextField(blank=True, db_column='ReviewNotes', null=True)),
                ('transferfrom', models.CharField(blank=True, db_column='TransferFrom', max_length=250, null=True)),
                ('transferto', models.CharField(blank=True, db_column='TransferTo', max_length=250, null=True)),
                ('dsareviewed', models.IntegerField(blank=True, db_column='DsaReviewed', null=True)),
                ('validfrom', models.DateTimeField(blank=True, db_column='ValidFrom', null=True)),
                ('validto', models.DateTimeField(blank=True, db_column='ValidTo', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblTransferRequest',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Tblassetgroups',
        ),
        migrations.DeleteModel(
            name='Tblassetschangelog',
        ),
        migrations.DeleteModel(
            name='Tblassetsregister',
        ),
        migrations.DeleteModel(
            name='Tbltransferrequests',
        ),
    ]
